version: '2'
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /data/nginx/conf:/etc/nginx
            - /data/web:/usr/share/nginx/www
        restart: on-failure:5
    ldap:
        build: ./ldap
        expose:
            - "389"
        environment:
            - SLAPD_PASSWORD={{ldap_password}}
            - SLAPD_DOMAIN={{domain}}
            - SLAPD_CONFIG_PASSWORD={{ldap_password}}
            - SLAPD_ADDITIONAL_SCHEMAS=inetorgperson
        volumes:
            - ldap_data:/var/lib/ldap
            - ldap_conf:/etc/openldap
        restart: on-failure:5
volumes:
    ldap_data:
        driver: local
    ldap_conf:
        driver: local
