version: '2'
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /data/nginx/conf:/etc/nginx
            - /data/web:/usr/share/nginx/www
        restart: always
    ldap:
        build: ./ldap
        expose:
            - "389"
        volumes:
            - /data/ldap/data:/var/lib/ldap
            - /data/ldap/conf:/etc/ldap/slap.d
